<?php

/**
 * @file
 * Contains penncourse.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function penncourse_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the penncourse module.
    case 'help.page.penncourse':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Displays course information from the Penn-In-Touch web service.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function penncourse_theme() {
  return [
    'penncourse' => [
      'render element' => 'children',
    ],
  ];
}
